@host=http://localhost:5250

POST {{host}}/auth/login
Content-Type: application/json

{
    "firstName": "Amichai",
    "lastName": "Mantinband",
    "email": "amichai@mantinband.com",
    "password": "Amiko1232!"
}