
GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NDZjN2VlZS0yZDNlLTQyMWUtODQ3OC02ODg3YjQ1OGFiOWUiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsImp0aSI6ImU4MjBiYzgxLTU2MTItNDk5Yi1iOTlmLTg4OGQzNmZiODMyZCIsImV4cCI6MTcwMzc5NDYxOCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.3sbN0G4fF5Hped5virZ9LGxVrB1pkrhBuHP97_dyo-8
